feeds:
  science:
    title: Научпоп
    link: http://example.com
    language: "ru"
    description: Землекоп и арзамас
    sources:
      - http://zemlekop.libsyn.com/rss
      - https://arzamas.academy/feed_v1/podcast.rss

  echo-msk:
    title: Эхо Москвы
    description: Фид избранных передач
    link: http://echo.msk.ru
    language: "ru"
    image: https://echo.msk.ru/programs/personalno/2759726-echo/
    sources:
      - http://www.echo.msk.ru/programs/graniweek/rss-audio.xml
      - http://www.echo.msk.ru/programs/tochka/rss-audio.xml
      - http://echo.msk.ru/programs/personalnovash/rss-audio.xml

settings:
  timeout: 60