feeds:
  science:
    title: Научпоп
    language: "ru"
    description: Землекоп и арзамас
    image: science.jpg
    sources:
      - http://zemlekop.libsyn.com/rss
      - https://arzamas.academy/feed_v1/podcast.rss
      - https://echo.msk.ru/programs/napalcah/rss-audio.xml

  echo-msk:
    title: Эхо Москвы
    description: Фид избранных передач
    link: http://echo.msk.ru
    language: "ru"
    image: echo_msk.png
    sources:
      - http://www.echo.msk.ru/programs/graniweek/rss-audio.xml
      - http://www.echo.msk.ru/programs/tochka/rss-audio.xml
      - http://echo.msk.ru/programs/personalnovash/rss-audio.xml
      - http://www.echo.msk.ru/programs/code/rss-audio.xml
      - https://echo.msk.ru/programs/belkovskytime/rss-audio.xml
      - https://echo.msk.ru/programs/nevsredy/rss-audio.xml
      - https://echo.msk.ru/programs/personalno/rss-audio.xml

settings:
  timeout: 60